version: "3.6"

services:

  redis:

    image: gerold/tutorial_redis:dev

    restart: "unless-stopped"

    volumes:
      - ./data/redis:/data


  flaskapp:

    image: gerold/tutorial_flaskapp:dev

    restart: "unless-stopped"

    depends_on:
      - redis

    environment:
      PRODUCTION: "true"


  nginx:

    image: gerold/tutorial_nginx:dev

    restart: "unless-stopped"

    depends_on:
      - flaskapp

    environment:
      PRODUCTION: "true"

    ports:
      - 8080:8080

